

SELECT * FROM customer LIMIT 10;

--1. Total revenue generated by male and female customers
SELECT gender, SUM(purchase_amount) AS revenue, COUNT(customer_id)
FROM customer
GROUP BY gender;

--2. customers who used discount but still paid more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

--3. top 5 products with the highest avg review rating
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating desc
LIMIT 5;

--4. Comparing avg purchase amounts b/w Standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


--5. Do subscribed customers spend more? Compare avg spend and total rev b/w subscribers and non subs
SELECT subscription_status,
COUNT(customer_id) AS number_of_customers,
ROUND(AVG(purchase_amount), 3) AS average_spend,
ROUND(SUM(purchase_amount), 3) AS revenue
FROM customer
GROUP BY subscription_status
ORDER BY revenue;


--6. Five products with highest % of purchases with discounts applied?
SELECT item_purchased,
ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)*100.0)/COUNT(*), 2) AS percentage
FROM customer
GROUP BY item_purchased
ORDER BY percentage desc
LIMIT 5;


--7. Segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 8 THEN 'Returning'
	ELSE 'Loyal'
	END as segment
FROM customer
)

SELECT segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY segment;


--8. Top 3 most purchased products within each category
WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


--9. Are repeat buyers (>5 previous purchases) likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;


--10. Revenue contribution of each age group.
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;



--11. Does customer demand vary by season across product categories and which categories should be prioritized for seasonal inventory and marketing planning?
SELECT category, season, SUM(purchase_amount) AS revenue, COUNT(*) AS orders
FROM customer
GROUP BY category, season 
ORDER BY category, revenue DESC;